-- Staff accounts for role-based access (owner authenticates via env password;
-- these are the additional employee logins). Idempotent.

create table if not exists users (
    id            bigint generated by default as identity primary key,
    username      varchar(80) unique not null,
    password_hash varchar(200) not null,
    role          varchar(20) default 'staff',
    active        boolean default true,
    created_at    timestamptz default now()
);
