-- Marketing engine: order attribution, append-only audit/event log, and
-- automation toggles. Idempotent; mirrors api/models_db.py.

alter table orders add column if not exists attribution jsonb not null default '{}'::jsonb;

create table if not exists audit_events (
    id          bigint generated by default as identity primary key,
    occurred_at timestamptz default now(),
    actor       varchar(80) default 'system',
    kind        varchar(60) not null,
    entity_type varchar(40) default '',
    entity_id   bigint,
    data        jsonb not null default '{}'::jsonb
);

create index if not exists idx_audit_events_kind on audit_events(kind);
create index if not exists idx_audit_events_entity on audit_events(entity_type, entity_id);
create index if not exists idx_audit_events_occurred_at on audit_events(occurred_at);

create table if not exists automations (
    kind             varchar(40) primary key,
    enabled          boolean default false,
    config           jsonb not null default '{}'::jsonb,
    last_run_at      timestamptz,
    last_run_ok      boolean,
    last_run_message varchar(400) default ''
);
