-- Catch-up migration: tables and columns added after the initial schema for
-- presets, inventory, co-packer orders, and preset-purchase order fields.
-- Idempotent; mirrors api/models_db.py.

-- Order columns added with the presets/checkout feature.
alter table orders add column if not exists preset_id      bigint;
alter table orders add column if not exists payment_status varchar(20) default 'unpaid';

create table if not exists presets (
    id             bigint generated by default as identity primary key,
    name           varchar(160) not null,
    description    varchar(400) default '',
    model_id       varchar(64) default '',
    shape          varchar(16) default 'straight',
    runs           jsonb not null default '[]'::jsonb,
    price_usd      double precision,
    verified_price boolean default false,
    ship_speed     varchar(16) default 'next_day',
    image_url      varchar(400) default '',
    active         boolean default true,
    created_at     timestamptz default now()
);

create table if not exists inventory_items (
    id            bigint generated by default as identity primary key,
    kind          varchar(20) not null,
    key           varchar(80) unique not null,
    name          varchar(160) default '',
    on_hand       double precision default 0,
    unit          varchar(24) default 'each',
    reorder_point double precision default 0,
    copacker      varchar(120) default '',
    updated_at    timestamptz default now()
);

create table if not exists copacker_orders (
    id               bigint generated by default as identity primary key,
    created_at       timestamptz default now(),
    copacker         varchar(120) default '',
    items            jsonb not null default '[]'::jsonb,
    status           varchar(20) default 'draft',
    trigger          varchar(40) default 'manual',
    related_order_id bigint,
    emailed          boolean default false,
    notes            varchar(400) default ''
);

-- inventory_items.key is already UNIQUE (implies an index), so no extra index needed.
create index if not exists idx_copacker_status on copacker_orders(status);
