-- Initial schema for the Modular Greenhouse System.
-- Mirrors the SQLAlchemy models in api/models_db.py. Written idempotently so it
-- coexists with the app's create_all() safety net.

create table if not exists fab_sessions (
    id          bigint generated by default as identity primary key,
    created_at  timestamptz default now(),
    week_of     date not null,
    label       varchar(120) default '',
    status      varchar(20) default 'planned'
);

create table if not exists orders (
    id              bigint generated by default as identity primary key,
    created_at      timestamptz default now(),
    customer_name   varchar(200) default '',
    customer_email  varchar(200) default '',
    model_id        varchar(64) not null,
    shape           varchar(16) not null,
    runs            jsonb not null default '[]'::jsonb,
    status          varchar(20) default 'quote',
    bom             jsonb not null default '[]'::jsonb,
    quote_lines     jsonb not null default '[]'::jsonb,
    pricing         jsonb not null default '{}'::jsonb,
    engineering     jsonb not null default '{}'::jsonb,
    source          varchar(20) default 'admin',
    contact         jsonb not null default '{}'::jsonb,
    external_refs   jsonb not null default '{}'::jsonb,
    shipping        jsonb not null default '{}'::jsonb,
    fab_session_id  bigint references fab_sessions(id)
);

create index if not exists idx_orders_status on orders(status);
create index if not exists idx_orders_fab_session on orders(fab_session_id);

create table if not exists integrations (
    id                bigint generated by default as identity primary key,
    provider          varchar(40) not null,
    label             varchar(120) default '',
    secret_blob       text not null,
    field_names       jsonb not null default '[]'::jsonb,
    enabled           boolean default true,
    created_at        timestamptz default now(),
    updated_at        timestamptz default now(),
    last_test_at      timestamptz,
    last_test_ok      boolean,
    last_test_message varchar(400) default ''
);

create table if not exists settings (
    key   varchar(64) primary key,
    value jsonb not null default '{}'::jsonb
);
